services:
  - type: web
    name: music-library-ls-oct22
    env:  node
    region:  frankfurt
    plan:  free
    buildCommand: npm ci
    startCommand: npm run migrate && node index.js
    envVars:
      - key: PGDATABASE
        fromDatabase:
          name: music_library_dev
          property: database
      - key: PGUSER
        fromDatabase:
          name: music_library_dev
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: music_library_dev
          property: password
      - key: PGHOST
        fromDatabase:
          name: music_library_dev
          property: host
      - key: PGPORT
        fromDatabase:
          name: music_library_dev
          property: port

databases:
  - name: music_library_dev
    plan: free
    region: frankfurt
    databaseName: music_library
    ipAllowList: []